= Suporte de resposta do Rastreador
:allow-uri-read: 




=== Suporte de resposta do Rastreador

O Tracker agora fornece respostas à API para que você possa ver a saída da API REST relacionada à tarefa.



=== Suporte de autenticação de link para o AWS Secrets Manager

Agora você tem a opção de usar segredos do AWS Secrets Manager para autenticar links para que você não precise usar credenciais armazenadas em cargas de trabalho do BlueXP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Conete-se a um sistema de arquivos FSX for ONTAP com um link do Lambda"]



=== Implemente as melhores práticas para um sistema de arquivos FSX for ONTAP

O BlueXP  workloads fornece um painel onde você pode verificar o status bem arquitetado das configurações do sistema de arquivos. Você pode aproveitar essa análise para implementar as práticas recomendadas para seus sistemas de arquivos FSX for ONTAP. A análise de configuração do sistema de arquivos inclui as seguintes configurações: Limite de capacidade SSD, snapshots locais programados, backups programados do FSX para ONTAP, disposição de dados em categorias e replicação de dados remota.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Saiba mais sobre a análise bem arquitetada para configurações do sistema de arquivos"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["Implemente as práticas recomendadas para seus sistemas de arquivos"]




=== Notificação bem arquitetada para problemas do sistema de arquivos

No console do BlueXP , os sistemas de arquivos FSX for ONTAP com problemas bem arquitetados agora exibem uma notificação no Canvas indicando quando os sistemas de arquivos têm problemas para corrigir.



=== Terminologia de permissões atualizada

A interface do usuário e a documentação de fábrica da carga de trabalho agora usam "somente leitura" para se referir a permissões de leitura e "leitura-gravação" para se referir a permissões de automação.
