= Associe o sistema de arquivos FSX for ONTAP com um espaço de trabalho no BlueXP 
:allow-uri-read: 




=== Associe o sistema de arquivos FSX for ONTAP com um espaço de trabalho no BlueXP 

Após a integração do BlueXP  em novembro de 2024, os sistemas de arquivos FSX para ONTAP recém-criados não foram associados a um workspace no BlueXP . Agora, quando você cria ou descobre os sistemas de arquivos FSX for ONTAP, eles estão associados a um espaço de trabalho em uma conta do BlueXP .

Se você já possui sistemas de arquivos FSX for ONTAP que não estão associados a um espaço de trabalho, ajudaremos você a associá-los a um espaço de trabalho no BlueXP . Você pode link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-get-help.html#create-a-case-with-netapp-support["Crie um caso com o suporte da NetApp"^]de dentro do console do BlueXP . Selecione *Workload Factory* como serviço.



=== Remoção do sistema de arquivos da tela BlueXP 

Agora você pode remover um sistema de arquivos FSX for ONTAP de uma área de trabalho na tela do BlueXP . Esta operação dissocia o sistema de arquivos de um workspace para que você possa associá-lo a outro workspace dentro da mesma conta do BlueXP .

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-remove-filesystem.html["Saiba como remover um sistema de arquivos FSX for ONTAP de uma área de trabalho no BlueXP "^]



=== Tracker disponível para operações de monitoramento e rastreamento

O Rastreador, uma nova funcionalidade de monitoramento, está disponível no BlueXP  Amazon FSX for NetApp ONTAP. Você pode usar o Rastreador para monitorar e rastrear o andamento e o status das credenciais, armazenamento e operações de link, analisar detalhes de tarefas e subtarefas de operação, diagnosticar problemas ou falhas, editar parâmetros para operações com falha e repetir operações com falha.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["Saiba como monitorar e acompanhar as operações do FSX for ONTAP no BlueXP "^]



=== CloudShell disponível nas cargas de trabalho do BlueXP 

O CloudShell está disponível quando você está em cargas de trabalho do BlueXP  no console do BlueXP . O CloudShell permite que você use as credenciais da AWS e do ONTAP fornecidas em sua conta do BlueXP  e execute os comandos da CLI da AWS ou da CLI do ONTAP em um ambiente semelhante a um shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html#before-you-begin["Use o CloudShell"^]
